name: account
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sembast: ^3.8.2
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/nonorder.png
    - assets/images/coffee.jpg
    - assets/images/green_tea.jpg
    - assets/images/chocolate_cake.jpg
    - assets/images/default.png
    - assets/images/bg.jpg